[workspace]
members = [
    "crates/lib/fuse-ffmpeg",
    "crates/lib/fuse-gui",
    "crates/lib/fuse-logger",
    "crates/lib/fuse-util",
    "crates/lib/sysmut",

    "crates/bin/fuse"
]
exclude = [
    "crates/lib/fuse-gui/assets"
]
