[package]
name = "fuse"
version = "0.1.0"
authors = [ "Lance Wallis <bleudeveloper@gmail.com>"]
edition = "2021"

[[bin]]
name = "Fuse"
path = "fuse.rs"

[dependencies]
fuse-util = { path = "../../lib/fuse-util" }
fuse-gui = { path = "../../lib/fuse-gui" }

self_update = { version = "0.37.0" }
libloading = "0.8.0"
notify = "6.0.1"
tokio = { version = "1.29", features = ["net", "rt-multi-thread"]}

[dependencies.windows]
version = "0.48.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading"
]

[features]
default = []
