[package]
name = "fuse"
version = "0.1.0"
authors = [ "Lance Wallis <bleudeveloper@gmail.com>"]
edition = "2021"

[[bin]]
name = "Fuse"
path = "fuse.rs"

[dependencies]
fuse-util = { path = "../../lib/fuse-util" }
fuse-gui = { path = "../../lib/fuse-gui" }

libloading = "0.7.2"
notify = "4.0.17"

[dependencies.windows]
version = "0.29.0"
features = [
    "alloc",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading"
]

[features]
default = []
